debug: false
server:
  port: 80
  servlet:
    context-path: /consumer
spring:
  application:
    name: consumer-service
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  cloud:
    loadbalancer:
      ribbon:
        # false:关闭ribbon，使用SpringCloud的LoadBalance。
        enabled: true #默认就是true
eureka:
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    service-url:
      #单机版
      #defaultZone: http://eureka7001.com:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
# openfeign详情参见官方文档https://cloud.spring.io/spring-cloud-static/spring-cloud-openfeign/2.2.0.RELEASE/reference/html/
feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 5000
logging:
  level:
    mjhct.springcloud.consumer.service.ProviderService: DEBUG