debug: false
server:
  port: 84
  servlet:
    context-path: /consumer
spring:
  application:
    name: sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #本应用接收sentinel规则的端口
        port: 8719
        #sentinel地址
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            serverAddr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            dataType: json
            ruleType: flow
feign:
  sentinel:
    enabled: true