debug: true
server:
  port: 80
  servlet:
    context-path: /consumer
spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES