debug: true
server:
  port: 8801
spring:
  application:
    name: stream-provider
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost
          defaultBrokerPort: 9092
      bindings:
        output:
          destination: myQueue
eureka:
  client:
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/