debug: false
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 不去检索服务
    fetch-registry: false
    serviceUrl:
      # 交互地址，查询服务和注册服务都用这个
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
      defaultZone: http://eureka7002.com:7002/eureka/ #集群版
